# Generated by Django 2.0.2 on 2018-03-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='фото')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=300, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(blank=True, max_length=300, verbose_name='название блюда')),
                ('complexity', models.SmallIntegerField(blank=True, default=0, verbose_name='сложность')),
                ('time', models.SmallIntegerField(blank=True, default=0, verbose_name='Время')),
                ('calories', models.SmallIntegerField(blank=True, default=0, verbose_name='каллории')),
                ('proteins', models.SmallIntegerField(blank=True, default=0, verbose_name='Белки')),
                ('fats', models.SmallIntegerField(blank=True, default=0, verbose_name='жиры')),
                ('carbohydrates', models.SmallIntegerField(blank=True, default=0, verbose_name='углеводы')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='цена за порцию')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='фото')),
                ('recipe', models.TextField(blank=True, default=None, verbose_name='рецепт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(blank=True, max_length=300, verbose_name='название эгридиента')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
                ('unit', models.SmallIntegerField(blank=True, default=0, verbose_name='единица измерения')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('calories', models.SmallIntegerField(blank=True, default=0, verbose_name='каллории')),
                ('proteins', models.SmallIntegerField(blank=True, default=0, verbose_name='Белки')),
                ('fats', models.SmallIntegerField(blank=True, default=0, verbose_name='жиры')),
                ('carbohydrates', models.SmallIntegerField(blank=True, default=0, verbose_name='углеводы')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=300, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='название')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='фото')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Kitchen'),
        ),
        migrations.AddField(
            model_name='dish',
            name='kitchen_goods',
            field=models.ManyToManyField(to='products.KitchenGoods', verbose_name='что должно быть дома'),
        ),
        migrations.AddField(
            model_name='bring',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Dish', verbose_name='блюдо'),
        ),
        migrations.AddField(
            model_name='bring',
            name='ingredients',
            field=models.ManyToManyField(to='products.Ingredient', verbose_name='ингредиент'),
        ),
    ]
